version: '3.2'

services:
    db:
        image: postgres
        volumes:
            - type: volume
              source: dbdata
              target: /var/lib/postgresql/data/

    app:
        image: zachzundel/digital-professors:1.0.0-alpha
        depends_on:
            - db
        command: ["gunicorn", "--access-logfile", "-", "--bind", "0.0.0.0:8000", "digitalprofessors.wsgi:application"] 
        volumes:
            - type: volume
              source: static
              target: /var/www/static

    serve:
        image: nginx
        ports:
            - "80:80"
        depends_on: 
            - app
        volumes:
            - type: volume
              source: static
              target: /var/www/static
            - ./nginx:/etc/nginx/conf.d

volumes:
    dbdata:
    static:
