# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20170815_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 19, 5, 22, 19, 917326)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 8, 19, 5, 22, 19, 917326)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='hourly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 8, 19, 5, 22, 49, 807019, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
