# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20170819_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutoring.SessionCategory'),
            preserve_default=False,
        ),
    ]
