# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20170819_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='wifi_password',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='wifi_ssid',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
