# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_auto_20170819_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Tutor')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.SessionTutor'),
        ),
    ]
