# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20170819_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontutor',
            name='tutor',
        ),
        migrations.AddField(
            model_name='session',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Tutor'),
        ),
        migrations.DeleteModel(
            name='SessionTutor',
        ),
    ]
