# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_auto_20170819_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='earnings_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
