# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_session_earnings_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CRDT', 'Credit Card'), ('CHCK', 'Check'), ('CASH', 'Cash')], default='CRDT', max_length=4),
        ),
    ]
