# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_session_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('', 'Select Payment Method'), ('CRDT', 'Credit Card'), ('CHCK', 'Check'), ('CASH', 'Cash')], max_length=4),
        ),
    ]
