# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_auto_20170819_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=7.25, max_digits=12),
            preserve_default=False,
        ),
    ]
