# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_professor_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='session',
            name='earnings_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='session',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
