# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_auto_20170819_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_method',
            field=models.CharField(choices=[('CRDT', 'Credit Card'), ('CHCK', 'Check'), ('CASH', 'Cash')], max_length=4),
        ),
    ]
