# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_auto_20170831_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessioncategory',
            options={'verbose_name_plural': 'Session Categories'},
        ),
    ]
