# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_auto_20170831_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PEND', 'Pending'), ('WAIT', 'Waiting for Parts'), ('CLOS', 'Closed'), ('OTHR', 'Other')], default='PEND', max_length=4),
            preserve_default=False,
        ),
    ]
