# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0017_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
