# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_auto_20170926_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=12),
        ),
    ]
