# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0019_professor_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
